apiVersion: v1
kind: Service
metadata:
  name: argocd-ingress
  labels:
    app.kubernetes.io/name: argocd-server
spec:
  ports:
  - port: 8080
  selector:
    app.kubernetes.io/name: argocd-server
  type: LoadBalancer


