apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: presto-gateway
  namespace: argocd-ns
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: {{ .Values.gateway.port }}
      name: http
      protocol: {{ .Values.gateway.protocol }}
    {{- if .Values.gateway.hosts }}
    {{- with .Values.gateway.hosts }}
    hosts:
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- end }}
  project: production
  source:
    path: argocd-rollouts/istioHelm/
    repoURL: https://github.com/Lokeshyogi/argocd-deploy.git
    targetRevision: HEAD
  destination:
    namespace: production
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true





