apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devops-toolkit
  namespace: argocd-ns
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: production
  source:
    path: argocd-rollouts/starburst-presto/
    repoURL: https://github.com/Lokeshyogi/argocd-deploy.git
    targetRevision: HEAD
  destination:
    namespace: production
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true

